### PR TITLE
sign up working

### PR DESCRIPTION
**Pull request by juanshishido**
Need an additional test, though. Currently at 92%.

### CODE REVIEW

**Comment by binnie869** [comment]
Any specific reason as to why you have removed comments from the code? I had specifically put them there to make it more readable.

**Comment by binnie869** [comment]
LGTM. Can merge once the tests are written.

**Comment by binnie869** [comment]
Merging so that I have the template to work on for pubnub.

**Comment by binnie869** [comment]
@juanshishido : You have become a pro :)

**Comment by juanshishido** [comment]
@binnie869: Just got a chance to look at this. Sorry for the delay.

I think readability is absolutely important (see [here](https://www.python.org/dev/peps/pep-0008/) and [here](https://github.com/amontalenti/elements-of-python-style)). As has been attributed to Guido, "code is read much more often than it is written."

The following example from Preeyanon, Pyrkosz, and Brown (2014, [link](https://osf.io/zqbu2/)) describes (and greatly influenced) my thoughts of this.

```
x += 1# add 1 to x
```

It's clear to see that we're adding `1` to `x`, but "the comment does not provide any information about the purpose of the statement or describe `x`."

We could, instead, choose to use the following comment.

```
x += 1 # increase the count of DNA sequences read in
```

We can do better, though.

```
sequence_count += 1 # increase the number of DNA sequences read by one
```

Now, because of the descriptive variable name, we don't even need the comment.

> This is a simple example of how code readability can be improved by choosing appropriate variable names and commenting code sparingly.

Where I removed comments&mdash;and I did not look at all cases&mdash;I thought the code was quite self-explanatory and that the comments were actually redundant.

**Pull request merged**
