### PR TITLE
Implementing Blueprints in the application

### PR DESCRIPTION
**Pull request by binnie869**
More about Blueprints http://flask.pocoo.org/docs/0.10/blueprints/

### CODE REVIEW

**Comment by juanshishido** [comment]
Nice work, @binnie869!

Two questions (mostly for my understanding):
- why is `not_found()` in `app/__init__.py` instead of something like `app/views.py` with a `@route` to `/404`?
- why are we redirecting to https://github.com/404?

Let me know and I'll go ahead and merge unless @hydrobase/core have any other comments.

Other than that, I think it looks great :+1:

**Comment by juanshishido** [comment]
One other thing I just noticed, `flask.render_template` is never used in `app/__init__.py` so we can remove it from the imports.

**Comment by binnie869** [comment]
- why is not_found() in app/**init**.py instead of something like app/views.py with a @route to /404?
  I will have to look this up but I think since its general to any module. That is if we redirect to a page that does not exist from any module it should redirect to 404 page. I need to look this up

why are we redirecting to https://github.com/404?
- We will have to create a 404 page for hydrobase. I could not find anything better so I just randomly redirected.

We can remove that. Will do it now.

**Comment by binnie869** [comment]
@juanshishido : Actually, we might need render template if we have our custom 404 page. So let it be there

**Comment by juanshishido** [comment]
Sounds good, @binnie869. Merging now :ok_hand: 

We currently don't have `not_found()` covered in any tests, but we can add that in a subsequent PR.

**Comment by juanshishido** [comment]
Seeing what the function does now:

redirecting

**Pull request merged**
